version: '2.1'
volumes:
  dbbackups:
  postgis-data:

services:

  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - postgis-data:/var/lib/postgresql
      - dbbackups:/backups
      - "./pgjwt-init.sh:/usr/local/bin/pgjwt-init.sh"
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=dwcalidadaire-final
      - POSTGRES_USER=gonzalomelo
      - POSTGRES_PASS=password
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5434:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
    command: 
      - pgjwt-init.sh

  dbbackups:
    image: kartoza/pg-backup:9.6
    hostname: pg-backups
    volumes:
      - dbbackups:/backups
    links:
      - db:db
    environment:
      - DUMPPREFIX=dwcalidadaire-final
      - PGUSER=gonzalomelo
      - PGPASSWORD=password
      - PGDATABASE=dwcalidadaire-final
      - PGPORT=5432
      - PGHOST=db
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

  stgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://gonzalomelo:password@db:5432/dwcalidadaire-final
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon