-- public.tiempo

-- ##########################
-- ETL
-- ##########################

-- public.ubicacionGeog_1

-- ##########################
-- Ver data.sql
-- ##########################

-- public.contaminantes

-- ##########################
-- Ver data.sql
-- ##########################

-- public.camaras

INSERT INTO camaras (iddetector, dscUbicacion) VALUES (1, 'Sarmiento - Requena - Rambla');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (2, 'Sarmiento - Requena - Rambla');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (3, 'Sarmiento - Requena - Rambla');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (5, 'Rambla - Morales - Jackson');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (6, 'Rambla - Morales - Jackson');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (7, 'Rambla - Morales - Jackson');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (9, 'Rambla - Errazquin - Sarmiento');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (10, 'Rambla - Errazquin - Sarmiento');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (12, 'Rambla - Errazquin - Sarmiento');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (19, 'Rambla - Montero - Solano Garcia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (20, 'Rambla - Montero - Solano Garcia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (22, 'Bv Espana - Ellauri - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (23, 'Bv Espana - Ellauri - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (25, 'Av Brasil - Ellauri - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (26, 'Av Brasil - Ellauri - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (28, 'Benito Blanco - 21 de Setiembre - Bv Espana');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (29, 'Benito Blanco - 21 de Setiembre - Bv Espana');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (31, 'Bv Espana - Rambla - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (32, 'Bv Espana - Rambla - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (33, 'Bv Espana - Rambla - Benito Blanco');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (35, 'Rambla - Montero - Bv Espana');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (36, 'Rambla - Montero - Bv Espana');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (37, 'Rambla - Montero - Bv Espana');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (39, 'Rambla - L A de Herrera - Buxareo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (40, 'Rambla - L A de Herrera - Buxareo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (42, '26 de Marzo - Bonavita - Tezanos');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (43, '26 de Marzo - Bonavita - Tezanos');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (45, 'Rambla - L A de Herrera - 26 de Marzo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (46, 'Rambla - L A de Herrera - 26 de Marzo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (47, 'Rambla - L A de Herrera - 26 de Marzo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (49, 'Rambla - Pereyra - Paiva');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (50, 'Rambla - Pereyra - Paiva');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (51, 'Rambla - Pereyra - Paiva');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (53, 'Solano Lopez - Rivera - Rambla');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (54, 'Solano Lopez - Rivera - Rambla');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (56, 'Rambla - Batlle y Ordonez - Solano Lopez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (57, 'Rambla - Batlle y Ordonez - Solano Lopez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (59, 'Rambla - Hipolito Yrigoyen - 9 de Junio');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (60, 'Rambla - Hipolito Yrigoyen - 9 de Junio');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (62, 'Rambla - Arrascaeta - Hipolito Yrigoyen');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (63, 'Rambla - Arrascaeta - Hipolito Yrigoyen');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (64, 'Rambla - Arrascaeta - Hipolito Yrigoyen');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (66, 'Rambla - Gral Paz - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (67, 'Rambla - Gral Paz - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (69, 'L A de Herrera - Placido Ellauri - 26 de Marzo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (70, 'L A de Herrera - Placido Ellauri - 26 de Marzo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (72, 'Benito Blanco - Buxareo - Julio Cesar');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (73, 'L A de Herrera - Rambla - 26 de Marzo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (74, '26 de Marzo - Rambla - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (75, '26 de Marzo - Rambla - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (77, 'Albo - 8 de Octubre - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (78, 'Albo - 8 de Octubre - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (80, 'Albo - 8 de Octubre - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (81, 'Albo - 8 de Octubre - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (82, 'Centenario - Jaime Cibils - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (83, 'Centenario - Jaime Cibils - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (85, 'Centenario - Jaime Cibils - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (86, 'Ricaldoni - Ponce - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (87, 'Ricaldoni - Ponce - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (89, 'Ricaldoni - Alfredo Navarro - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (90, 'Ricaldoni - Alfredo Navarro - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (91, 'Ricaldoni - Alfredo Navarro - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (93, 'Av Italia - Avelino Miranda - Albo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (94, 'Av Italia - Avelino Miranda - Albo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (96, 'Av Italia - Avelino Miranda - Albo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (97, 'Av Italia - L A de Herrera - Las Heras');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (98, 'Av Italia - L A de Herrera - Las Heras');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (99, 'Av Italia - L A de Herrera - Las Heras');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (101, 'Batlle y Ordonez - Malbajar - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (102, 'Batlle y Ordonez - Malbajar - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (104, 'Comercio - 8 de Octubre - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (105, 'L A de Herrera - Rep Dominicana - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (106, 'L A de Herrera - Rep Dominicana - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (108, 'Batlle y Ordonez - Ramon Anador - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (109, 'Batlle y Ordonez - Ramon Anador - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (111, 'Solano Lopez - Rivera - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (112, 'Av Italia - Las Heras - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (113, 'Av Italia - Las Heras - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (115, 'Av Italia - Las Heras - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (116, 'Av Italia - Mataojo - Solano Lopez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (117, 'Av Italia - Mataojo - Solano Lopez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (118, 'Av Italia - Mataojo - Solano Lopez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (120, 'Hipolito Yrigoyen - Igua - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (121, 'Hipolito Yrigoyen - Rivera - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (122, 'Hipolito Yrigoyen - Rivera - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (124, 'Av Italia - Solano Lopez - Mataojo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (125, 'Av Italia - Solano Lopez - Mataojo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (126, 'Av Italia - Solano Lopez - Mataojo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (128, 'Av Italia - Gallinal - Hipolito Yrigoyen');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (129, 'Av Italia - Gallinal - Hipolito Yrigoyen');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (131, 'Av Italia - Gallinal - Hipolito Yrigoyen');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (132, 'Av Italia - Hipolito Yrigoyen - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (133, 'Av Italia - Hipolito Yrigoyen - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (134, 'Av Italia - Hipolito Yrigoyen - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (136, 'Av Italia - Bolivia - Zum Felde');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (137, 'Av Italia - Bolivia - Zum Felde');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (139, 'Bolivia - Cno Carrasco - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (140, 'Bolivia - Cno Carrasco - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (142, 'Bolivia - Rivera - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (143, 'Bolivia - Rivera - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (145, 'Av Italia - Zum Felde - Bolivia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (146, 'Av Italia - Zum Felde - Bolivia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (148, 'Av Italia - Cooper - Bolonia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (149, 'Av Italia - Cooper - Bolonia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (151, 'Ponce - Rivera - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (152, 'Av Brasil - Brito del Pino - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (153, 'Av Brasil - Brito del Pino - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (155, 'Rivera - Ponce - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (156, 'Rivera - Ponce - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (158, 'Bv Espana - Libertad - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (159, 'Bv Espana - Libertad - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (161, '21 de setiembre - Sarmiento - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (162, 'Rodo - Requena - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (163, 'Rodo - Requena - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (165, 'Rodo - Requena - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (166, 'Canelones - Acevedo Diaz - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (167, 'Canelones - Acevedo Diaz - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (172, '21 de setiembre - Bv Espana - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (173, 'Bv Artigas - Bv Espana - Canelones');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (174, 'Bv Artigas - Bv Espana - Canelones');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (176, 'Bv Artigas - Sosa - 21 de setiembre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (177, 'Bv Artigas - Sosa - 21 de setiembre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (179, 'Bv Artigas - Palmar - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (180, 'Bv Artigas - Palmar - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (181, 'Bv Artigas - Palmar - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (183, 'Bv Artigas - Ponce - Canelones');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (184, 'Bv Artigas - Ponce - Canelones');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (185, 'Bv Artigas - Ponce - Canelones');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (187, 'Avelino Miranda - 8 de Octubre - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (188, 'Avelino Miranda - 8 de Octubre - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (190, 'Avelino Miranda - 8 de Octubre - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (194, 'Acevedo Diaz - Garibaldi - Ferrer Serra');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (195, 'Acevedo Diaz - Garibaldi - Ferrer Serra');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (196, 'Acevedo Diaz - Garibaldi - Ferrer Serra');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (198, 'Miguelete - Justicia - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (200, 'Miguelete - Justicia - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (205, 'Daniel Munoz - Martin C Martinez - Acevedo Diaz');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (206, 'Daniel Munoz - Martin C Martinez - Acevedo Diaz');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (207, 'Daniel Munoz - Martin C Martinez - Acevedo Diaz');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (209, 'Victor Haedo - Paullier - Acevedo Diaz');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (210, 'Victor Haedo - Paullier - Acevedo Diaz');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (212, 'Victor Haedo - Paullier - Acevedo Diaz');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (213, 'Bv Artigas - Canning - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (214, 'Bv Artigas - Canning - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (216, 'Bv Artigas - Canning - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (217, 'Bv Artigas - Palmar - Canaro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (218, 'Bv Artigas - Palmar - Canaro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (219, 'Bv Artigas - Palmar - Canaro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (225, 'Av Italia - Avelino Miranda - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (226, 'Av Italia - Avelino Miranda - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (228, 'Av Italia - Avelino Miranda - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (229, 'Bv Artigas - Hocquart - Miguelete');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (230, 'Bv Artigas - Hocquart - Miguelete');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (232, 'Bv Artigas - Hocquart - Miguelete');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (233, 'Bv Artigas - Goes - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (234, 'Bv Artigas - Goes - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (235, 'Bv Artigas - Goes - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (236, 'Bv Artigas - Goes - Av Italia');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (238, 'Nueva Palmira - Monte Caseros - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (239, 'Nueva Palmira - Monte Caseros - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (241, 'Hocquart - Justicia - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (242, 'Hocquart - Justicia - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (248, 'Bv Artigas - Hocquart - Nueva Palmira');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (249, 'Bv Artigas - Hocquart - Nueva Palmira');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (250, 'Bv Artigas - Hocquart - Nueva Palmira');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (251, 'Garibaldi - Monte Caseros - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (252, 'Garibaldi - Monte Caseros - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (254, 'Bv Artigas - Colorado - Caribes');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (255, 'Bv Artigas - Colorado - Caribes');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (256, 'Bv Artigas - Colorado - Caribes');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (258, 'Bv Artigas - Colorado - Caraguata');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (259, 'Bv Artigas - Colorado - Caraguata');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (260, 'Bv Artigas - Colorado - Caraguata');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (262, 'Bv Artigas - L A de Herrera - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (263, 'Bv Artigas - L A de Herrera - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (264, 'Bv Artigas - L A de Herrera - Gallinal');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (266, 'Varela - Batlle y Ordonez - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (267, 'Varela - Batlle y Ordonez - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (269, 'L A de Herrera - Setembrino Pereda - Varela S');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (270, 'L A de Herrera - Setembrino Pereda - Varela S');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (272, 'Bv Artigas - Gallinal - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (273, 'Bv Artigas - Gallinal - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (274, 'Bv Artigas - Gallinal - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (276, 'Aramburu - Terra - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (278, 'Aramburu - Terra - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (279, 'Amezaga - Arenal Grande - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (280, 'Gral Flores - Av de las Leyes - Yatay');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (281, 'Gral Flores - Av de las Leyes - Yatay');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (283, 'Gral Flores - Blandengues - Aramburu');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (284, 'Gral Flores - Aramburu - Blandengues');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (286, 'Gral Flores - Aramburu - Blandengues');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (290, 'Garibaldi - Pando - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (291, 'Gral Flores - Gallinal - Garibaldi');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (293, 'Gral Flores - Gallinal - Garibaldi');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (294, 'L A de Herrera - Gualeguay - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (295, 'L A de Herrera - Gualeguay - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (297, 'L A de Herrera - Gualeguay - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (301, 'L A de Herrera - Gral San Martin - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (302, 'Bv Artigas - Penco - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (303, 'Bv Artigas - Penco - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (305, 'Bv Artigas - Penco - Gral Flores');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (306, 'Gral Flores - Gallinal - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (307, 'Gral Flores - Gallinal - Bv Artigas');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (309, 'Gral Flores - Quesada - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (310, 'Gral Flores - Quesada - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (312, 'Garibaldi - Urquiza - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (313, 'Garibaldi - Urquiza - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (315, 'L A de Herrera - Francisco Simon - Asilo');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (316, 'Garibaldi - Centenario - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (317, 'Garibaldi - Centenario - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (319, 'L A de Herrera - Monte Caseros - Joanico');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (321, 'Larranaga - Monte Caseros - Joanico');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (322, 'Larranaga - Monte Caseros - Joanico');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (324, 'Centenario - Cibils - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (325, 'Centenario - Cibils - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (326, 'Centenario - Cibils - L A de Herrera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (328, 'Batlle y Ordonez - Joanico - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (329, 'Batlle y Ordonez - Joanico - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (331, 'Batlle y Ordonez - Joanico - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (332, 'Battle y Ordonez - Cabrera - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (333, 'Battle y Ordonez - Cabrera - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (335, 'Battle y Ordonez - Cabrera - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (336, '8 de octubre - Cibils - Mariano Moreno');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (337, '8 de octubre - Cibils - Mariano Moreno');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (338, '8 de octubre - Cibils - Mariano Moreno');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (340, '8 de Octubre - Avelino Miranda - Presidente Berro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (341, '8 de Octubre - Avelino Miranda - Presidente Berro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (343, '8 de octubre - Mariano Moreno - Cibils');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (344, '8 de octubre - Mariano Moreno - Cibils');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (346, 'Joanico - Bv Batlle y Ordonez - Larranaga');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (348, '8 de Octubre - Sanguinetti - Batlle y Ordonez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (349, '8 de Octubre - Sanguinetti - Batlle y Ordonez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (351, 'Comercio - Joanico - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (352, 'Larravide - Isla de Gaspar - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (353, 'Raissignier - Cno Carrasco - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (354, 'Raissignier - Cno Carrasco - 8 de Octubre');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (356, '8 de Octubre - Battle y Ordonez - Sanguinetti');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (357, '8 de Octubre - Battle y Ordonez - Sanguinetti');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (358, '8 de Octubre - Battle y Ordonez - Sanguinetti');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (360, '8 de Octubre - Serrato - Cipriano Miro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (361, '8 de Octubre - Serrato - Cipriano Miro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (363, '8 de Octubre - Serrato - Cipriano Miro');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (364, '8 de Octubre - Gral Villagran - Raissignier');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (365, '8 de Octubre - Gral Villagran - Raissignier');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (367, '8 de Octubre - Cipriano Miro - Serrato');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (368, '8 de Octubre - Cipriano Miro - Serrato');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (370, 'Soca - Brito del Pino - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (371, 'Soca - Brito del Pino - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (373, 'Ponce - Ricaldoni - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (374, 'Soca - Gestido - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (375, 'Ponce - Av Brasil - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (376, 'Rivera - Bv Artigas - Ponce');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (377, 'Rivera - Bv Artigas - Ponce');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (379, 'Rivera - Rosell y Rius - 14 de Julio');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (380, 'Rivera - Rosell y Rius - 14 de Julio');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (382, 'L A de Herrera - Demostenes - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (383, 'L A de Herrera - Placido Ellauri - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (384, 'L A de Herrera - Placido Ellauri - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (386, 'Rivera - 14 de Julio - Rosell y Rius');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (387, 'Rivera - 14 de Julio - Rosell y Rius');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (389, 'Rivera - Batlle y Ordonez - Tezanos');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (390, 'Rivera - Batlle y Ordonez - Tezanos');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (392, 'Batlle y Ordonez - Ramon Anador - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (393, 'Batlle y Ordonez - Ramon Anador - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (395, 'Solano Lï¿½pez - Av Italia - Asamblea');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (396, 'Solano Lï¿½pez - Av Italia - Asamblea');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (398, 'Batlle y Ordonez - Pereyra - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (399, 'Batlle y Ordonez - Pereyra - Rivera');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (401, 'Rivera - Tezanos - Batlle y Ordonez');
INSERT INTO camaras (iddetector, dscUbicacion) VALUES (402, 'Rivera - Tezanos - Batlle y Ordonez');

-- public.mediciones

